[features]
seeds = false
skip-lint = false
[programs.localnet]
simple_contract = "4J9r4AoVd2wyg5TKwVBQrqj47JVi4FAWXp9eY5Rutg9s"

[registry]
url = "https://api.apr.dev"

[provider]


[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
